name: docker-compose-phpunit-functional

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docker-compose-phpunit-functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run docker compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./tools/docker-dev/docker-compose.yml"
    - name: Execute tests in the running services
      run: |
        docker compose exec -w '/var/www/unity-web-portal' web composer update
    - name: Execute tests in the running services
      run: |
        docker compose exec -w '/var/www/unity-web-portal' web ./vendor/bin/phpunit --testsuite=functional
